package gis.jvm;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import gis.shared.Generators;
import gis.shared.Graph;
import gis.shared.Graphs;
import gis.shared.algorithms.SCCBasedAlgorithm;
import org.scalacheck.Gen;
import scala.Tuple3;
import scala.collection.immutable.Stream;
import scala.runtime.AbstractFunction1;

import javax.swing.*;
import java.awt.*;
import java.util.HashMap;
import java.util.Map;

import static gis.jvm.View.GraphType.CONNECTED;
import static gis.jvm.View.GraphType.DISCONNECTED;

public class View extends JFrame {
    public static final int WINDOW_WIDTH = 1200;
    public static final int WINDOW_HEIGHT = 800;
    private JPanel mainPanel;
    private JButton nextStepButton;
    private JComboBox<String> predefinedComboBox;
    private JPanel graphPanel1;
    private JButton generateDisconnectedButton;
    private JButton generateConnectedButton;
    private JTextField verticesNumTextField;
    private JProgressBar algorithmProgressBar;
    private JTabbedPane tabbedPane1;
    private JPanel graphPanel2;

    GraphVisualization graphVisualization = new GraphVisualization(graphPanel1);

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(panel1, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(10, 1, new Insets(30, 30, 30, 30), -1, -1));
        panel1.add(panel2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(90, 396), null, 0, false));
        predefinedComboBox = new JComboBox();
        panel2.add(predefinedComboBox, new GridConstraints(9, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        nextStepButton = new JButton();
        nextStepButton.setText("Next step");
        nextStepButton.setMnemonic('N');
        nextStepButton.setDisplayedMnemonicIndex(0);
        panel2.add(nextStepButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_NONE, 1, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        generateDisconnectedButton = new JButton();
        generateDisconnectedButton.setText("Generate Disconnected");
        panel2.add(generateDisconnectedButton, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setFont(UIManager.getFont("InternalFrame.titleFont"));
        label1.setText("Predefined graphs");
        panel2.add(label1, new GridConstraints(8, 0, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setFont(UIManager.getFont("InternalFrame.titleFont"));
        label2.setText("Generation");
        panel2.add(label2, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setFont(UIManager.getFont("InternalFrame.titleFont"));
        label3.setText("Algorithm");
        panel2.add(label3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        generateConnectedButton = new JButton();
        generateConnectedButton.setText("Generate Connected");
        panel2.add(generateConnectedButton, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        verticesNumTextField = new JTextField();
        verticesNumTextField.setText("");
        verticesNumTextField.setToolTipText("Enter vertices number");
        panel2.add(verticesNumTextField, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Vertices number");
        panel2.add(label4, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        algorithmProgressBar = new JProgressBar();
        panel2.add(algorithmProgressBar, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tabbedPane1 = new JTabbedPane();
        panel1.add(tabbedPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(200, 200), null, 0, false));
        graphPanel1 = new JPanel();
        graphPanel1.setLayout(new GridBagLayout());
        tabbedPane1.addTab("First Step", graphPanel1);
        graphPanel2 = new JPanel();
        graphPanel2.setLayout(new GridBagLayout());
        tabbedPane1.addTab("Second Step", graphPanel2);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    public enum GraphType {
        DISCONNECTED,
        CONNECTED
    }

    public View() {
        super("Graph Visualization");
        setUp();
    }

    private void setUp() {
        this.setContentPane(mainPanel);
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.setSize(WINDOW_WIDTH, WINDOW_HEIGHT);
        setUpPredefinedComboBox(predefinedComboBox);
        this.setVisible(true);

        nextStepButton.addActionListener((e) -> {
            algorithmProgressBar.setValue(algorithmProgressBar.getValue() + 1);
            graphVisualization.nextStep();
            SwingUtilities.updateComponentTreeUI(this);
        });
        generateDisconnectedButton.addActionListener(e -> generateGraph(getVerticesNum(), DISCONNECTED));
        generateConnectedButton.addActionListener(e -> generateGraph(getVerticesNum(), CONNECTED));
        tabbedPane1.addChangeListener(l -> {
            for (Component component : tabbedPane1.getComponents()) {
                component.setVisible(false);
            }
            tabbedPane1.getSelectedComponent().setVisible(true);
        });
    }

    private int getVerticesNum() {
        return Integer.parseInt(verticesNumTextField.getText());
    }

    private void generateGraph(int verticesNum, GraphType graphType) {
        Graph graph = getGeneratedGraph(verticesNum, graphType);
        graphVisualization = new GraphVisualization(graphPanel1);
        Tuple3<Stream<Stream<Object>>, Graph, Object> solution = new SCCBasedAlgorithm(graph).solve();
        algorithmProgressBar.setValue(0);
        algorithmProgressBar.setMaximum(solution._1().size());
        graphVisualization.visualize(solution, graph);
        initSecondGraph(solution, graphVisualization);
        SwingUtilities.updateComponentTreeUI(this);
    }

    private Graph getGeneratedGraph(final int verticesNum, GraphType graphType) {
        Gen<Graph> graphGen = graphType == DISCONNECTED ? Generators.notPartiallyConnected() : Generators.partiallyConnected();
        return graphGen.suchThat(new AbstractFunction1<Graph, Object>() {
            @Override
            public Object apply(Graph v1) {
                return v1.vertices().size() < verticesNum;
            }
        }).sample().get();
    }


    private void setUpPredefinedComboBox(JComboBox<String> comboBox) {
        Map<String, Graph> graphMap = new HashMap<>();
        Graphs.partiallyConnectedGraphs().foreach(new AbstractFunction1<Graph, String>() {
            @Override
            public String apply(Graph g) {
                String itemName = "partially connected - " + comboBox.getItemCount();
                graphMap.put(itemName, g);
                comboBox.addItem(itemName);
                return itemName;
            }
        });
        Graphs.notPartiallyConnectedGraphs().foreach(new AbstractFunction1<Graph, String>() {
            @Override
            public String apply(Graph g) {
                String itemName = "not partially connected - " + comboBox.getItemCount();
                graphMap.put(itemName, g);
                comboBox.addItem(itemName);
                return itemName;
            }
        });
        comboBox.addActionListener(e -> visualizeGraph(comboBox, graphMap));
    }

    private void visualizeGraph(JComboBox<String> comboBox, Map<String, Graph> graphMap) {
        graphVisualization = new GraphVisualization(graphPanel1);
        String selectedItem = (String) comboBox.getSelectedItem();
        Graph selectedGraph = graphMap.get(selectedItem);
        Tuple3<Stream<Stream<Object>>, Graph, Object> solution = new SCCBasedAlgorithm(selectedGraph).solve();
        algorithmProgressBar.setValue(0);
        algorithmProgressBar.setMaximum(solution._1().size());
        graphVisualization.visualize(solution, selectedGraph);
        initSecondGraph(solution, graphVisualization);

        SwingUtilities.updateComponentTreeUI(this);
    }

    private void initSecondGraph(Tuple3<Stream<Stream<Object>>, Graph, Object> solution, GraphVisualization firstStepGraph) {
        GraphVisualization graphVisualization = new GraphVisualization(graphPanel2);
        graphVisualization.visualizeGraph(solution._2());
        graphVisualization.graphView().setStylesheet(firstStepGraph.graphView().getStylesheet());
        graphVisualization.colorVertices(firstStepGraph.colors());
    }
}
